name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.6.0'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Run Development Servers
        run: |
          npm run dev:backend &

          sleep 5

          npm run dev:frontend &

          sleep 5

      - name: Test Web App
        run: |
          npm test