name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.6.0'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build